package Presentacion.Comando.Comando;


public enum IDEventos {
	
	EVENTO_MAIN,
	EVENTO_ERROR,
	
	//Eventos de Empleados
	
	EVENTO_ALTA_EMPLEADO,
	EVENTO_BAJA_EMPLEADO,
	EVENTO_CALCULAR_NOMINA_EMPLEADO,
	
	
	//Eventos de Departamento
	
	EVENTO_ALTA_DEPARTAMENTO,
	EVENTO_BAJA_DEPARTAMENTO,
	EVENTO_CONSULTAR_DEPARTAMENTO,
	EVENTO_LISTAR_DEPARTAMENTOS,
	EVENTO_MODIFICAR_DEPARTAMENTO,
	EVENTO_CALCULAR_NOMINA_DEPARTAMENTO,
}